config:
  path: ~/deep_clustering_for_wce/src/dumps/see_ai_processed_training
  img_size: 224
  seed: 23
  training:
    epochs: 300
    batch_size: 32
    num_workers: 4
    learning_rate: 6.25e-05
    weight_decay: 0.05
    optimizer: adamw
    precision: 16
    scheduler:
      name: cosine
      warmup_epochs: 10
  momentum_schedule:
    base_momentum: 0.996
    final_momentum: 1.0
  dino_loss:
    output_dim: 65536
    warmup_teacher_temp: 0.04
    teacher_temp: 0.07
    warmup_teacher_temp_epochs: 10
    student_temp: 0.1
    center_momentum: 0.9
  transforms:
    global_crop_size: 224
    global_crop_scale:
    - 0.5
    - 1.0
    local_crop_size: 160
    local_crop_scale:
    - 0.3
    - 0.5
    n_local_views: 4
    hf_prob: 0.5
    vf_prob: 0.5
    rr_prob: 0.5
    cj_prob: 0.8
    cj_strength: 0.7
    cj_bright: 0.4
    cj_contrast: 0.4
    cj_sat: 0.2
    cj_hue: 0.0
    random_gray_scale: 0.2
    gaussian_blur:
    - 1.0
    - 0.1
    - 0.0
    sigmas:
    - 0.1
    - 2.0
    solarization_prob:
    - 0.0
    - 0.0
    normalize:
      mean:
      - 0.5929
      - 0.3667
      - 0.1843
      std:
      - 0.1932
      - 0.1411
      - 0.094
pretrained: true
